name: Prod Deploy Frontend
on:
  release:
    types:
      - created

jobs:
  prod-deploy-frontend-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM Install
        run: |
          cd packages/frontend/
          npm install --production
      - name: Production Build
        run: |
          cd packages/frontend/
          npm run build-production
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: |
          cd packages/frontend
          aws s3 rm s3://automa2n-prod-frontend --recursive
          aws s3 sync build/ s3://automa2n-prod-frontend
